<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageReference Include="Umbraco.Cms.Core" />
        <PackageReference Include="Umbraco.Cms.Web.Common" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Models\Casko.XmlSitemapsForUmbraco.Models.csproj" />
    </ItemGroup>

</Project>
