<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);IncludeProjectReferenceBuildOutput</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>

    <PropertyGroup>
        <Product>Casko.XmlSitemapsForUmbraco</Product>
        <PackageId>Casko.XmlSitemapsForUmbraco</PackageId>
        <Title>XML Sitemaps for Umbraco</Title>
        <Description>XML Sitemaps for Umbraco helps Umbraco projects publish XML sitemaps in a structured, configurable way. It is designed for teams that want reliable sitemap delivery for search engines without having to build and maintain the full solution themselves.</Description>
        <PackageTags>umbraco;umbraco-marketplace;xml-sitemap</PackageTags>
        <Authors>Casper Korsgaard</Authors>
        <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Casper Korsgaard</Copyright>
        <PackageProjectUrl>https://github.com/hallojoe/xml-sitemaps-for-umbraco</PackageProjectUrl>
        <RepositoryUrl>https://github.com/hallojoe/xml-sitemaps-for-umbraco</RepositoryUrl>
        <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageIcon></PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
        <PackageReference Include="Umbraco.Cms.Web.Website"/>
        <PackageReference Include="Umbraco.Cms.Web.Common"/>
        <PackageReference Include="Umbraco.Cms.Api.Common"/>
        <PackageReference Include="Umbraco.Cms.Api.Management"/>
    </ItemGroup>

    <ItemGroup>
        <!-- Dont include the client folder as part of packaging nuget build -->
        <Content Remove="Client\**"/>

        <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
        <None Include="Client\public\umbraco-package.json" Pack="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\docs\README_nuget.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Common\Casko.XmlSitemapsForUmbraco.Common.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Models\Casko.XmlSitemapsForUmbraco.Models.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Providers\Casko.XmlSitemapsForUmbraco.Providers.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Providers.Examine\Casko.XmlSitemapsForUmbraco.Providers.Examine.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Storage\Casko.XmlSitemapsForUmbraco.Storage.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Storage.UmbracoMedia\Casko.XmlSitemapsForUmbraco.Storage.UmbracoMedia.csproj" />
        <ProjectReference Include="..\Casko.XmlSitemapsForUmbraco.Delivery\Casko.XmlSitemapsForUmbraco.Delivery.csproj" />
    </ItemGroup>
    
    <ItemGroup>
      <Folder Include="wwwroot\App_Plugins\" />
    </ItemGroup>

    <Target Name="IncludeProjectReferenceBuildOutput" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)" Condition="'%(ReferenceCopyLocalPaths.ReferenceSourceTarget)' == 'ProjectReference'" />
        </ItemGroup>
    </Target>

</Project>
