// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44341' | (string & {});
};

export type XmlSitemapConfigurationResponse = {
    enabled: boolean;
    rewritesEnabled: boolean;
    renderAlternateLinksForSingleCultureSitemaps: boolean;
    rootNodeSearchLevel: number;
    sitemapCount: number;
    customSitemapCount: number;
    indexCount: number;
    globalFilters: XmlSitemapGlobalFiltersResponse;
    storage?: XmlSitemapStorageConfigurationResponse | null;
    sitemaps: Array<XmlSitemapConfigurationRowResponse>;
    customSitemaps: Array<XmlSitemapCustomConfigurationRowResponse>;
    indexes: Array<XmlSitemapIndexConfigurationRowResponse>;
};

export type XmlSitemapConfigurationRowResponse = {
    key: string;
    publicName: string;
    path?: string | null;
    hostName?: string | null;
    culture?: string | null;
    includedCultures: Array<string>;
    excludedCultures: Array<string>;
    includedDocumentTypeAliases: Array<string>;
    excludedDocumentTypeAliases: Array<string>;
};

export type XmlSitemapCustomConfigurationRowResponse = {
    key: string;
    publicName: string;
    providerAlias?: string | null;
    hostName?: string | null;
    settingCount: number;
    settingKeys: Array<string>;
};

export type XmlSitemapGlobalFiltersResponse = {
    includedContentTypeAliases: Array<string>;
    excludedContentTypeAliases: Array<string>;
    includedCultures: Array<string>;
    excludedCultures: Array<string>;
    excludingUrlPropertyAlias?: string | null;
    excludingUrlPropertyValue?: string | null;
};

export type XmlSitemapIndexConfigurationRowResponse = {
    key: string;
    publicName: string;
    hostName?: string | null;
    sitemaps: Array<string>;
    publicSitemaps: Array<string>;
};

export type XmlSitemapStorageConfigurationResponse = {
    refreshStaleAfterSeconds: number;
    backgroundJobEnabled: boolean;
    backgroundJobIntervalSeconds?: number | null;
};

export type GetConfigurationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/xmlsitemapsforumbraco/api/v1/configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: XmlSitemapConfigurationResponse;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];
